"""On-policy C1 mission data for the C3-v3 round (pre-declared 30 Sep 2026, commit ec2e34c9).

A mission's causal contexts are read with the offline pipeline's `Recording`: native policy
histories, physics trace, and frames regenerated by verified replay. The context checks are
identical to `Recording.native`; `causal_context_complete` applies them without loading pixels.
"""
import json
from pathlib import Path

import numpy as np

from lewm.c3v2_offline_pipeline_development import Recording

BASE = Path('/home/andrewknowles/RecoveryStorage/LeWMQuad-v3/.generated/navigation_development_artifacts_v1/'
            'go2_navigation_capability_v1_attempt_001')
REPLAYS = BASE/'c3v3_onpolicy_replays'
FIT, HELDOUT = range(16), range(16, 22)


def run_name(maze):
    return f'c3v3_onpolicy_C1_m{maze:02d}_ep0_attempt001'


def run_recording(run, replay):
    n = Path(run)/'native'
    return Recording(n/'policy_histories.npz', n/'policy_observations.json', lambda i: Path(replay)/'ego_frames'/f'{i:04d}.png',
                     n/'physics_trace.npz')


def recording_for(row):
    """Recording for a training or evaluation row: on-policy rows carry their replay directory."""
    return run_recording(row['directory'], row['replay']) if row.get('replay') else Recording.training_case(row['directory'])


def camera_frames(run):
    return json.loads((Path(run)/'native/in_memory_camera_observations.json').read_text())['frames']


def causal_context_complete(recording, frame):
    """Recording.native's checks, without pixels."""
    indices = (frame-10, frame-5, frame)
    if min(indices) < 0:
        return False
    expected = [recording.stamps[i] for i in indices]
    if np.diff(expected).tolist() != [500_000_000]*2:
        return False
    values, measured, available = recording.values[frame], recording.measured[frame], recording.available[frame]
    return bool(recording.valid[frame].all() and np.array_equal(measured[[4, 9, 14]], expected)
                and np.all(np.diff(measured) == 100_000_000) and not np.any(measured > expected[-1])
                and not np.any(available > expected[-1]) and not np.any(values[:, 1] != 0))
