"""Keep original registration and use the tiled-density floor kernel privately."""
from lewm import floor_pose_registration_development as plane
from lewm.measured_floor_transport_registration_development import MeasuredFloorTransportRegistration
from lewm.eligible_floor_registration_development import bind
from lewm.tiled_density_routed_floor_cell_index_development import observed_floor_cell_index

measured_candidates=bind(plane.measured_candidates,observed_floor_cell_index=observed_floor_cell_index)


class TiledDensityFloorRegistration(MeasuredFloorTransportRegistration):
    observe=bind(MeasuredFloorTransportRegistration.observe,measured_candidates=measured_candidates)
