"""Interpretation-only analysis of C4's inputs (Andrew Knowles, 28 September 2026).

C4 receives the candidate command tape directly, so it may mostly learn kinematics.
Nothing here changes any controller or result.

Part A (logs only): C4's logged motion predictions versus C1's command-history
forecasts, which the shared runtime computes and logs on the same decision inputs.
Part B: native model inputs for a fixed decision sample are regenerated by a
verified deterministic replay of logged C4 episodes (no new outcomes), then C4
is re-evaluated with its own visual features (must reproduce the log) and with
visual features swapped from another decision (other maze; same maze later).
"""
import argparse
from collections import deque
from concurrent.futures import ProcessPoolExecutor
import contextlib
from functools import partial
import json
import math
from multiprocessing import get_context
from pathlib import Path

import numpy as np
import torch

from lewm import decision_headroom_json_v42_development as output
from scripts import run_go2_navigation_capability_completed_support_v4_development as owner
from scripts.render_go2_navigation_capability_pipeline_development import RecordedPrediction

HORIZONS_MS = list(range(100, 801, 100))
SAMPLE_EPISODES = (10, 11, 12)   # lowest validation IDs, fixed before any analysis
SAMPLE_STRIDE = 5                # every fifth decision
WITHIN_OFFSET = 40               # same-maze swap partner: 40 decisions later (~16 s), wrapping


def runs(base):
    return sorted((base/'runs').glob('v4_completed_support_validation_C4_val*_ep0_attempt001'))


def wrap(yaw):
    return (yaw+np.pi) % (2*np.pi)-np.pi


def part_a(base):
    per_h = {h: dict(dxy=[], dyaw=[], c4_spread=[], c1_spread=[]) for h in range(8)}
    rank_same = rank_n = 0
    spearman = []
    decisions = 0
    for root in runs(base):
        calls = {r['observed_ns']: np.asarray(r['motion_xy_yaw']) for r in json.loads((root/'model_calls.json').read_text())}
        for plan in json.loads((root/'planning.json').read_text()):
            mc = plan.get('motion_correction')
            if 'selection' not in plan or mc is None or plan['measured_ns'] not in calls:
                continue
            c4 = calls[plan['measured_ns']]
            c1 = np.asarray(mc['command_history_forecast_xy_yaw'])
            assert np.allclose(c4[:, :, :2], np.asarray(mc['raw_forecast_xy_m']), atol=1e-6)
            decisions += 1
            for h in range(8):
                per_h[h]['dxy'].extend(np.linalg.norm(c4[:, h, :2]-c1[:, h, :2], axis=1))
                per_h[h]['dyaw'].extend(np.degrees(np.abs(wrap(c4[:, h, 2]-c1[:, h, 2]))))
                per_h[h]['c4_spread'].append(float(np.linalg.norm(c4[:, h, :2]-c4[:, h, :2].mean(0), axis=1).mean()))
                per_h[h]['c1_spread'].append(float(np.linalg.norm(c1[:, h, :2]-c1[:, h, :2].mean(0), axis=1).mean()))
            a, b = c4[:, 7, 0], c1[:, 7, 0]
            rank_same += int(np.argmax(a) == np.argmax(b))
            rank_n += 1
            ra, rb = np.argsort(np.argsort(a)), np.argsort(np.argsort(b))
            spearman.append(1-6*np.sum((ra-rb)**2)/(6*35))
    table = {f'{HORIZONS_MS[h]}ms': dict(
        c4_minus_c1_xy_m=dict(median=float(np.median(v['dxy'])), p90=float(np.percentile(v['dxy'], 90))),
        c4_minus_c1_yaw_deg=dict(median=float(np.median(v['dyaw'])), p90=float(np.percentile(v['dyaw'], 90))),
        c4_candidate_spread_xy_m=float(np.median(v['c4_spread'])), c1_candidate_spread_xy_m=float(np.median(v['c1_spread'])))
        for h, v in per_h.items()}
    return dict(decisions=decisions, episodes=len(runs(base)), per_horizon=table,
        same_best_forward_candidate_800ms=rank_same/rank_n, spearman_forward_800ms_mean=float(np.mean(spearman)),
        note='C1 forecasts are the runtime-logged command_history_forecast_xy_yaw computed on the same decision inputs.')


class Capture(RecordedPrediction):
    """Replays logged outputs; keeps the exact native model inputs for sampled decisions."""
    def __init__(self, receipts, arm, sample):
        super().__init__(receipts, arm)
        self.sample, self.native, self.inputs = sample, None, {}

    def set_native_context(self, packets, *, observed_ns):
        from lewm.dense_native_observation_development import dense_native_context
        self.native = dense_native_context(packets, observed_ns=observed_ns)
        self.current = observed_ns

    def forward(self, *, observation_history, known_action_blocks, known_action_valid):
        if self.current in self.sample:
            self.inputs[self.current] = dict(native=self.native, blocks=known_action_blocks.detach().cpu().clone(),
                                              valid=known_action_valid.detach().cpu().clone())
        return super().forward(observation_history=observation_history, known_action_blocks=known_action_blocks,
                               known_action_valid=known_action_valid)


def capture(base, root, out):
    """Verified replay of one logged C4 episode; saves sampled native inputs."""
    from lewm.navigation_capability_completed_support_development import CompletedSupportRuntimeMixin
    from lewm.navigation_capability_paired_floor_start_development import initialize_mapping
    from lewm.navigation_capability_target_reference_development import install_task_cues
    source = owner.source
    protocol = json.loads(owner.PROTOCOL.read_text())
    spec = json.loads((root/'specification.json').read_text())
    requests = json.loads((root/'requests.json').read_text())
    receipts = json.loads((root/'model_calls.json').read_text())
    frames = json.loads((root/'native/in_memory_camera_observations.json').read_text())['frames']
    plans = {r['frame']: r for r in json.loads((root/'planning.json').read_text()) if 'selection' in r}
    sample = set(r['observed_ns'] for r in receipts[::SAMPLE_STRIDE])
    model = Capture(receipts, 'C4', sample)
    budget = owner.Budget(base, protocol)
    clock = source.UntimedSimulationClock()
    controller = session = None
    source.previous.warmup()
    source.previous.study.cohort.stable.floor.configure()
    source.initialize_genesis(backend='cpu', seed=spec['procedural_seed'], logging_level='warning')
    work = out/f'{root.name}_replay'
    work.mkdir(parents=True)
    try:
        with contextlib.ExitStack() as stack:
            def pool(initializer):
                return stack.enter_context(ProcessPoolExecutor(max_workers=1, mp_context=get_context('spawn'), initializer=initializer))
            registration = pool(source.previous.study.previous.reference.previous.initialize_registration)
            mapping = pool(initialize_mapping)
            pose = pool(partial(source.initialize_pose, str(work)))
            obstacles = pool(source.previous.study.previous.reference.previous.initialize_obstacles)
            assert registration.submit(source.previous.native.baseline.registration_ready).result()
            assert mapping.submit(source.mapping_ready).result()
            assert pose.submit(source.pose_ready).result()
            assert obstacles.submit(source.previous.study.cohort.stable.obstacles_ready).result()
            (work/'native').mkdir()
            session = owner.make_session(spec, work/'native', full_frames=False)
            session.install_contact_identity()
            source.configure_gains(session.ctx.build.robot, session.ctx.runner._leg_dof_idx.tolist(), session.ctx.policy.env_cfg, 'checkpoint')
            session.settle_recorded()
            source.admit_context_setup(session, owner.sha(owner.__file__))
            cues = json.loads((root/'public_task_cues.json').read_text())
            runtime = type('StartupRecoveredRuntime', (CompletedSupportRuntimeMixin, source.DenseNavigationRuntime), {})
            controller = runtime(model, goal_initial_xy=cues['goal_initial_body_xy_m'], condition='jepa', variant='full', clock_ns=clock,
                evidence_sink=lambda *a: None, planning_delay_ticks=3, maximum_initial_dispatch_lateness_ns=0, prediction_source='neural',
                registration_executor=registration, navigation_ticks=4800, arrival_radius_m=.02, mapping_executor=mapping,
                pose_executor=pose, obstacle_executor=obstacles)
            install_task_cues(controller, cues)
            session.physics_clock_callback = clock.advance
            history = deque(maxlen=4)
            for tick, expected in enumerate(requests):
                budget.check()
                now = int(session.ctx.runner._sim_time_ns)
                clock.advance(now)
                assert now == expected['simulator_ns']
                if tick % 5 == 0:
                    policy, depth, fast, aux_depth, aux_rgb, measured = session.sensor_packets()
                    history.append(policy)
                    record = session.captured_pairs[-1]['consumed_hash_record']
                    for key in ('pixel_sha256', 'consumed_packet_sha256', 'measured_ns'):
                        assert record[key] == frames[tick//5][key], ('consumed packet differs', tick//5, key)
                    acquired = source.AcquiredFrame(tick//5, measured, policy, depth, fast, aux_rgb, aux_depth, tuple(history))
                    controller.submit(acquired)
                    owner.drain(controller, model, session, budget)
                    plan = plans.get(acquired.frame)
                    actual = next((r for r in reversed(controller.planning) if r['frame'] == acquired.frame and 'selection' in r), None)
                    assert (plan is None) == (actual is None) and (plan is None or plan['selection']['action'] == actual['selection']['action'])
                request = controller.request(now_ns=clock())
                assert request['requested_command'] == expected['requested_command'] and request['reason'] == expected['reason']
                session.phase = 2
                np.testing.assert_array_equal(session.command_policy_step(request['requested_command']), expected['applied_command'])
            controller.finish()
    finally:
        if controller is not None:
            controller.stopped.set()
            for thread in controller.threads:
                thread.join(timeout=2.)
        clock.close()
        if session is not None:
            session.ctx.build.scene.destroy()
        source.shutdown_genesis()
    assert set(model.inputs) == sample, 'every sampled decision captured'
    torch.save(dict(assignment=root.name, inputs=model.inputs, receipts={r['observed_ns']: r for r in receipts if r['observed_ns'] in sample}),
               out/f'{root.name}_inputs.pt')
    return len(sample)


def part_b(base, out):
    from lewm.navigation_capability_direct_slot_development import load as load_direct
    protocol = json.loads(owner.PROTOCOL.read_text())
    model = load_direct(protocol)
    device = next(model.predictor.parameters()).device
    episodes = [torch.load(out/f'v4_completed_support_validation_C4_val{m:02d}_ep0_attempt001_inputs.pt', weights_only=False) for m in SAMPLE_EPISODES]
    keyed = [sorted(e['inputs']) for e in episodes]

    def run(native, item):
        model.pending_context = native
        with torch.inference_mode():
            result = model(observation_history=None, known_action_blocks=item['blocks'].to(device), known_action_valid=item['valid'].to(device))
        return np.asarray(model.receipts[-1]['motion_xy_yaw'])
    rows = dict(reproduction_max_abs=0., other_maze=[], same_maze_later=[], c4_candidate_spread=[], command_swap=[])
    for e, (episode, keys) in enumerate(zip(episodes, keyed)):
        other_episode, other_keys = episodes[(e+1) % len(episodes)], keyed[(e+1) % len(episodes)]
        for i, key in enumerate(keys):
            item = episode['inputs'][key]
            own = run(item['native'], item)
            logged = np.asarray(episode['receipts'][key]['motion_xy_yaw'])
            rows['reproduction_max_abs'] = max(rows['reproduction_max_abs'], float(np.abs(own-logged).max()))
            partners = dict(other_maze=other_episode['inputs'][other_keys[i % len(other_keys)]],
                            same_maze_later=episode['inputs'][keys[(i+WITHIN_OFFSET//SAMPLE_STRIDE) % len(keys)]])
            for name, partner in partners.items():
                swapped = run(dict(item['native'], pixels=partner['native']['pixels']), item)
                rows[name].append(dict(dxy=np.linalg.norm(swapped[:, :, :2]-own[:, :, :2], axis=2),
                                       dyaw=np.degrees(np.abs(wrap(swapped[:, :, 2]-own[:, :, 2])))))
            # Reference: swap the command history instead of the image (same candidate tapes).
            partner = partners['other_maze']
            history = run(dict(item['native'], past_applied_commands=partner['native']['past_applied_commands']), item)
            rows['command_swap'].append(dict(dxy=np.linalg.norm(history[:, :, :2]-own[:, :, :2], axis=2),
                                             dyaw=np.degrees(np.abs(wrap(history[:, :, 2]-own[:, :, 2])))))
            rows['c4_candidate_spread'].append(np.linalg.norm(own[:, :, :2]-own[:, :, :2].mean(0), axis=2).mean(0))

    def summary(items):
        dxy = np.stack([r['dxy'] for r in items])
        dyaw = np.stack([r['dyaw'] for r in items])
        return {f'{HORIZONS_MS[h]}ms': dict(xy_change_m_median=float(np.median(dxy[:, :, h])), xy_change_m_p90=float(np.percentile(dxy[:, :, h], 90)),
                yaw_change_deg_median=float(np.median(dyaw[:, :, h])), yaw_change_deg_p90=float(np.percentile(dyaw[:, :, h], 90))) for h in (2, 7)}
    spread = np.stack(rows['c4_candidate_spread'])
    return dict(decisions=sum(len(k) for k in keyed), episodes=[f'{m}/0' for m in SAMPLE_EPISODES], stride=SAMPLE_STRIDE,
        own_features_reproduce_log_max_abs=rows['reproduction_max_abs'],
        visual_swap_other_maze=summary(rows['other_maze']), visual_swap_same_maze_later=summary(rows['same_maze_later']),
        command_history_swap_other_maze=summary(rows['command_swap']),
        c4_candidate_spread_xy_m={f'{HORIZONS_MS[h]}ms': float(np.median(spread[:, h])) for h in (2, 7)},
        method='Swap replaces only the three native RGB context frames; command history and candidate tapes are the decision\'s own.')


if __name__ == '__main__':
    p = argparse.ArgumentParser()
    p.add_argument('--phase', choices=('logs', 'capture', 'swap'), required=True)
    p.add_argument('--out', type=Path, required=True)
    args = p.parse_args()
    protocol = json.loads(owner.PROTOCOL.read_text())
    base = Path(protocol['output_root'])
    assert args.out.resolve().is_relative_to(base.resolve())
    output.install(base)
    args.out.mkdir(parents=True, exist_ok=True)
    if args.phase == 'logs':
        result = part_a(base)
        owner.save(args.out/'c4_vs_c1_logged_agreement.json', result)
    elif args.phase == 'capture':
        result = {m: capture(base, base/f'runs/v4_completed_support_validation_C4_val{m:02d}_ep0_attempt001', args.out) for m in SAMPLE_EPISODES}
    else:
        result = part_b(base, args.out)
        owner.save(args.out/'c4_visual_swap.json', result)
    print(json.dumps(result, indent=1)[:4000])
