import copy,hashlib,json,subprocess
from pathlib import Path
P=Path('docs/go2_decision_headroom_protocol_v4_2026-09-23.json')
original=json.loads(subprocess.check_output(['git','show','e30ced94:'+str(P)]));assert original==json.loads(P.read_text())
x=copy.deepcopy(original)
x.update(schema='go2_decision_headroom_protocol.v4.1',status='FROZEN_EXPLICIT_PHASE2_APPROVAL',phase2_authorized=True,historical_rerender_authorized=True,
 authority='User approval of e30ced94 as V4.1 with listed amendments; exact text and this JSON SHA-256 are bound in the approval record',
 entrypoint='scripts/run_go2_headroom_v41_development.py --approval docs/go2_decision_headroom_v41_approval_2026-09-23.json',
 execution_order=[0,4,1,5,2,6,3,7])
c=x['execution_caps'];c['phase']='Explicitly approved Phase 2 V4.1';c['phase2_approved']=True
c['blinding']='V4 six-state implementation checks only before approval; comparative scoring approved for this frozen V4.1 identity only.'
c['compute_caps']['execution_wall_seconds']=72*3600;c['compute_caps']['aggregate_cpu_seconds']=1152*3600
c['compute_caps']['comparative_selections_or_rankings']='Explicit Phase 2 V4.1 approval recorded with exact configuration SHA-256'
x['historical_rerender_proposal']['authorized']=True
x['historical_rerender_execution']=dict(entrypoint='scripts/check_go2_headroom_historical_rerender_v41_development.py',order='separate owner before Phase 2 launch',outcome_gates_launch=False,caps='unchanged historical_rerender_proposal',missing_inputs='unresolved; no new rendering adapter, trajectory regeneration, retries or substitutions',populations=dict(factorial_predictor_ancestor='training rows of retained factorial_manifest.json; current and first future RGB',native_predictor_training='retained current horizon predictor samples.json; current and assigned horizon RGB',full_heading_readout_training='retained full-heading collection training samples.json',maze_view_readout_training='retained maze-view collection training samples.json'),hash_priority='SHA256(str(seed)+"/"+population+"/"+example_id); lexical priority and ID; four per population before image inspection')
x['continuous_regret']=dict(primary='unzeroed continuous cost differences',near_tie='0.10 s applies only to set membership, including top-1 agreement; no zeroing, clipping or rounding of continuous regret')
f=x['filter_primary'];f['quantities']=['excluded_safe/safe','all_movement_excluded_and_any_safe/determinate_states'];f.update(reference_motion='R2',paired_contrast_rows=['R4/old_data','R4/maze_data','R5c'],primary_definition='six paired state-matched layout-level differences from R2 plus the two R2 levels',pairing='excluded-safe uses identical resolved safe candidates in the same states; complete exclusion uses states with both event labels determined; inverse-inclusion weights identical on both sides; equal source-cell weights within layout',descriptive='All per-source levels and admitted-but-unsafe rates: 95% intervals')
x['inference'].update(primary_family_size=13,primary_confidence=1-.05/13)
x['memo_rules']=dict(tau_rate_difference=.10,condition_A="A head's complete-exclusion-despite-safety difference from R2 has a lower bound above tau, and R5c's difference does not. Report: learned motion pathway causes false safety exclusions.",condition_B="Either the R2 complete-exclusion-despite-safety level, counting only states whose binding rule is memory clearance or stopping projection, has a lower bound above tau; or R5c's difference from R2 also exceeds tau. Report: motion-dependent gate is over-conservative independent of prediction quality.",both='Single recommendation addresses B first',neither='Use the unchanged handoff regret decision table',inconclusive='Inconclusive regret supports neither stopping nor continuing',missing_R5c_interval='A unresolved; missing evidence is not an observed lower bound that fails to exceed tau',binding_attribution='Original determinate-state denominator. Positive R2 event counts for B(i) only if every known-safe movement is bound by memory clearance or stopping projection; any unresolved candidate safety makes this attribution unresolved; observation-only binding is not motion-gate binding.',binding_interval='Same layout estimator and 1-0.05/13 confidence for the predeclared B(i) restriction of the R2 level; report separately from unrestricted primary level. The 13-quantity family concerns the primary panel, not a blanket simultaneous guarantee over every diagnostic.',coverage='V4 quantity-specific coverage applies; report each exposure stratum without selecting a favourable scope')
x['secondary_reference']=dict(label='secondary inflation-escape reference',primary_unchanged=True,eligibility='only hard-physically-safe complete branches; operating margin remains separately required for regret',extension='For physically safe endpoints inside 0.46-m inflation, nearest inflation-free grid cell reachable through non-inflated free space; add the path length to primary geodesic distance from that cell',nearest='shortest path distance on existing 20-mm eight-neighbour grid; lexicographic cell tie break; no search over target cost',point_free_path='zero-radius obstacle geometry; conservative cell/segment occupancy; no diagonal corner cutting; reference convention, not articulated safety evidence',entry='existing primary free-cell definition, including unchanged 5-mm clearance and half-cell-diagonal allowance',heading='unchanged primary heading at entry cell; all physical cost weights, arrival and braking components unchanged',missing='If nearest entry has no qualified target path, unresolved; never choose a different entry to obtain a favourable cost',clearance_strata=['inside_046m_inflation','outside_inflation_below_5mm','reference_free'],physical_strata='Cross each with articulated hard/operating safe, unsafe, unresolved; report candidate cost and reference-regret coverage under both references',repeat='Same predetermined spot-check states and 0.025-s cost range; no additional branches')
x['localisation_covariate']=dict(evaluator_only=True,frames='believed observed-map pose transformed via captured map_from_initial and the unchanged first-source-camera physical anchor; compared with native true decision pose',quantities=['horizontal_error_m','translation_error_m','yaw_error_rad','rotation_error_rad'],position_bins_m=[.02,.10],absolute_yaw_bins_degrees=[5,15],justification='20-mm operating/grid scale and 100-mm larger drift; 5/15-degree fixed heading bins, not chosen from audit outcomes',unavailable='explicit unresolved stratum; excludes only this covariate stratification',analysis='Descriptive regret and filter results at 95% intervals; no scorer, reference target or candidate input correction')
newfiles=['lewm/decision_headroom_v41_development.py','scripts/run_go2_headroom_v41_development.py','scripts/run_go2_headroom_v41_source_development.py','scripts/run_go2_headroom_v41_branches_development.py','scripts/read_go2_headroom_v41_development.py','scripts/check_go2_headroom_v41_development.py','scripts/check_go2_headroom_historical_rerender_v41_development.py']
for name in newfiles:
 p=Path(name);x['frozen_bindings'][name]=dict(sha256=hashlib.sha256(p.read_bytes()).hexdigest(),bytes=p.stat().st_size)
q=Path('docs/go2_decision_headroom_protocol_v41_2026-09-23.json');q.write_text(json.dumps(x,indent=2)+'\n');sha=hashlib.sha256(q.read_bytes()).hexdigest();q.with_suffix('.sha256').write_text(sha+'  '+q.name+'\n')
allowed={('schema',),('status',),('phase2_authorized',),('historical_rerender_authorized',),('authority',),('entrypoint',),('execution_order',),('historical_rerender_execution',),('continuous_regret',),('memo_rules',),('secondary_reference',),('localisation_covariate',),('execution_caps','phase'),('execution_caps','phase2_approved'),('execution_caps','blinding'),('execution_caps','compute_caps','execution_wall_seconds'),('execution_caps','compute_caps','aggregate_cpu_seconds'),('execution_caps','compute_caps','comparative_selections_or_rankings'),('historical_rerender_proposal','authorized'),('filter_primary',),('inference','primary_family_size'),('inference','primary_confidence')}
allowed|={('frozen_bindings',name) for name in newfiles}
diffs=[]
def compare(a,b,path=()):
 if a==b:return
 if isinstance(a,dict) and isinstance(b,dict):
  for k in sorted(set(a)|set(b)):
   if k not in a or k not in b:diffs.append(dict(path=list(path+(k,)),before=a.get(k),after=b.get(k)))
   else:compare(a[k],b[k],path+(k,))
 else:diffs.append(dict(path=list(path),before=a,after=b))
compare(original,x)
assert all(any(tuple(d['path'][:len(prefix)])==prefix for prefix in allowed) for d in diffs)
assert x['execution_input_bindings']==original['execution_input_bindings']
assert x['assignments']==original['assignments'] and x['sampling']==original['sampling']
assert x['reference_cost']==original['reference_cost'] and x['thresholds']==original['thresholds']
assert all(x['frozen_bindings'][k]==v for k,v in original['frozen_bindings'].items())
unchanged_caps=copy.deepcopy(x['execution_caps']);unchanged_caps['compute_caps']['execution_wall_seconds']=172800;unchanged_caps['compute_caps']['aggregate_cpu_seconds']=2764800;unchanged_caps['compute_caps']['comparative_selections_or_rankings']=original['execution_caps']['compute_caps']['comparative_selections_or_rankings']
assert unchanged_caps['compute_caps']==original['execution_caps']['compute_caps']
for k in ('collection_caps','branch_caps','storage_caps'):assert x['execution_caps'][k]==original['execution_caps'][k]
record=dict(status='PASS',baseline_commit='e30ced94',baseline_sha256=hashlib.sha256(P.read_bytes()).hexdigest(),protocol_sha256=sha,differences=diffs,models_controllers_layouts_original_bindings_unchanged=True,other_caps_unchanged=True,unlisted_differences=[])
Path('docs/go2_decision_headroom_v41_diff_check_2026-09-23.json').write_text(json.dumps(record,indent=2)+'\n')
print('PASS',sha,'changes',len(diffs))
