#!/usr/bin/env python3
"""Fresh Genesis box/projection development assay, NOT Go2 qualification.

No experiment imports, datasets, checkpoints, training, robot connection or
source export. Output directory must not exist; no retry overwrites evidence.
Physics is CPU; request software OpenGL explicitly in the launch environment.
"""
from __future__ import annotations

import argparse
import hashlib
import importlib.metadata
import json
import math
import os
from pathlib import Path
import sys
import traceback
from types import SimpleNamespace

ROOT = Path(__file__).resolve().parents[1]
for path in (ROOT, ROOT / "lewm_genesis", ROOT / "lewm_worlds"):
    if str(path) not in sys.path:
        sys.path.insert(0, str(path))

import numpy as np

from lewm.physical_semantics import blue_marker_centroid, evaluate_cases, project_world, world_from_optical

WIDTH, HEIGHT, HFOV = 640, 480, 78.323
DT, STEPS, SEED = 0.002, 400, 9042026
MARKER = (2.0, 0.4, 0.7)


def array(value):
    return value.detach().cpu().numpy() if hasattr(value, "detach") else np.asarray(value)


def capture(camera):
    rgb = array(camera.render(rgb=True)[0])
    if rgb.shape != (HEIGHT, WIDTH, 3) or rgb.dtype != np.uint8:
        raise ValueError(f"unexpected renderer RGB: {rgb.shape}, {rgb.dtype}")
    return np.ascontiguousarray(rgb)


def collect_case(name, output):
    from PIL import Image
    import genesis as gs
    from lewm_genesis.scene_builder import initialize_genesis, shutdown_genesis
    from lewm_genesis.scene_loader import genesis_vertical_fov_deg

    print(f"collecting {name}", flush=True)
    scene = None
    initialize_genesis(backend="cpu", seed=SEED, logging_level="warning")
    try:
        scene = gs.Scene(
            sim_options=gs.options.SimOptions(dt=DT, gravity=(0, 0, 0)),
            vis_options=gs.options.VisOptions(ambient_light=(1, 1, 1)),
            renderer=gs.renderers.Rasterizer(), show_viewer=False,
        )
        # Same collision material in both colored-wall cases. Appearance only
        # changes the render surface. No labels are generated by an analytic ray.
        if name != "clear":
            color = (1.0, 0.03, 0.03) if name == "wall_red" else (0.03, 1.0, 0.03)
            scene.add_entity(gs.morphs.Box(pos=(1.2, 0, 0.5), size=(0.2, 1, 1), fixed=True),
                             surface=gs.surfaces.Default(color=color))
        scene.add_entity(gs.morphs.Box(pos=MARKER, size=(0.06, 0.06, 0.06),
                                       fixed=True, collision=False),
                         surface=gs.surfaces.Default(color=(0.01, 0.01, 1.0)))
        probe = scene.add_entity(gs.morphs.Box(pos=(0.5, 0, 0.5), size=(0.2, 0.2, 0.2),
                                               visualization=False))
        camera = scene.add_camera(
            res=(WIDTH, HEIGHT), pos=(0, 0, 0.5), lookat=(1, 0, 0.5), up=(0, 0, 1),
            fov=genesis_vertical_fov_deg(SimpleNamespace(
                native_resolution=(WIDTH, HEIGHT), fov_deg=HFOV, fov_axis="horizontal")),
            near=0.05, far=200, GUI=False,
        )
        scene.build()
        rgb = capture(camera)
        Image.fromarray(rgb).save(output / f"{name}.png")
        projection_errors = []
        if name == "clear":
            for yaw in (0.0, math.radians(10)):
                forward = np.array([math.cos(yaw), math.sin(yaw), 0])
                transform = world_from_optical([0, 0, 0.5], forward, [0, 0, 1])
                camera.set_pose(pos=(0, 0, 0.5), lookat=forward + [0, 0, 0.5], up=(0, 0, 1))
                image = capture(camera)
                expected = project_world(MARKER, transform)
                measured = blue_marker_centroid(image)
                projection_errors.append(float(np.linalg.norm(expected - measured)))
                if yaw:
                    Image.fromarray(image).save(output / "clear_yaw10.png")
        probe.set_dofs_velocity([1, 0, 0, 0, 0, 0])
        positions = [array(probe.get_pos()).reshape(3).tolist()]
        first_contact = None
        for step in range(1, STEPS + 1):
            scene.step()
            positions.append(array(probe.get_pos()).reshape(3).tolist())
            contacts = probe.get_contacts()
            count = int(array(contacts["valid_mask"]).sum()) if "valid_mask" in contacts else len(contacts["geom_a"])
            if count and first_contact is None:
                first_contact = step
        probe.set_pos((0.5, 0, 0.5), zero_velocity=True)
        scene.step()
        reset_error = float(np.linalg.norm(array(probe.get_pos()).reshape(3) - [0.5, 0, 0.5]))
        reset_speed = float(np.linalg.norm(array(probe.get_vel()).reshape(3)))
        return {"rgb": rgb, "positions_m": positions, "first_contact_step": first_contact,
                "projection_error_px": projection_errors, "reset_position_error_m": reset_error,
                "reset_speed_mps": reset_speed}
    finally:
        try:
            if scene is not None:
                scene.destroy()
        finally:
            shutdown_genesis()


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", required=True, type=Path)
    args = parser.parse_args(argv)
    output = args.output_dir.absolute()
    for part in output.parts:
        if part in {"sealed", "sealed_test.json"} or part.startswith("sealed_"):
            parser.error("protected output path forbidden")
    output.mkdir(exist_ok=False)  # parent must already exist; never overwrite
    bindings = {}
    for relative in ("scripts/run_physical_semantics_development_v1.py", "lewm/physical_semantics.py",
                     "lewm/interface_semantics.py", "lewm_genesis/lewm_genesis/scene_loader.py",
                     "lewm_genesis/lewm_genesis/scene_builder.py"):
        bindings[relative] = hashlib.sha256((ROOT / relative).read_bytes()).hexdigest()
    report = {"schema": "physical_semantics_development.v1", "source_sha256": bindings,
              "scope": "independent primitive-box Genesis diagnostic; not Go2 or handoff qualification",
              "seed": SEED, "physics_dt_s": DT, "steps_per_case": STEPS,
              "camera": {"width": WIDTH, "height": HEIGHT, "horizontal_fov_deg": HFOV},
              "environment": {key: os.environ.get(key) for key in
                              ("LIBGL_ALWAYS_SOFTWARE", "PYOPENGL_PLATFORM", "EGL_PLATFORM", "EGL_DEVICE_ID")}}
    report["versions"] = {name: importlib.metadata.version(name)
                          for name in ("genesis-world", "numpy", "torch", "PyOpenGL")}
    # Native crashes cannot reach Python's exception handler. Preserve launch
    # identity first; missing result.json then means incomplete, never PASS.
    (output / "launch.json").write_text(json.dumps(report, indent=2, allow_nan=False) + "\n")
    try:
        cases = {}
        report["cases"] = {}
        for name in ("clear", "wall_red", "wall_green"):
            cases[name] = collect_case(name, output)
            case = dict(cases[name])
            case["rgb_sha256"] = hashlib.sha256(case.pop("rgb").tobytes()).hexdigest()
            report["cases"][name] = case
            (output / f"{name}_trace.json").write_text(json.dumps(case, indent=2, allow_nan=False) + "\n")
        report.update(evaluate_cases(cases))
    except Exception as exc:
        report.update(status="INFRASTRUCTURE_FAILURE", error=f"{type(exc).__name__}: {exc}")
        traceback.print_exc()
    (output / "result.json").write_text(json.dumps(report, indent=2, allow_nan=False) + "\n")
    print(json.dumps({key: value for key, value in report.items() if key not in ("cases", "source_sha256")}, indent=2))
    return 0 if report["status"] == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
