#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYTHON="${PYTHON:-$ROOT/.generated/venvs/genesis_render_vulkan/bin/python}"
OUT_DIR="${OUT_DIR:-$ROOT/.generated/go2_memory_closed_loop/generalized_learned_local_suite_20260629}"
POLICY="${POLICY:-$OUT_DIR/generalized_learned_local_gru.pt}"
POST_CLAIM_POLICY="${POST_CLAIM_POLICY:-}"
POST_CLAIM_POLICY_OUTCOME_RERANK="${POST_CLAIM_POLICY_OUTCOME_RERANK:-inherit}"
LEARNED_LOCAL_TARGET_POLICY_CHECKPOINTS="${LEARNED_LOCAL_TARGET_POLICY_CHECKPOINTS:-}"
LEARNED_LOCAL_TARGET_POLICY_STATE_CHECKPOINTS="${LEARNED_LOCAL_TARGET_POLICY_STATE_CHECKPOINTS:-}"
LEARNED_LOCAL_TARGET_POLICY_PRIORITY_OVER_POST_CLAIM="${LEARNED_LOCAL_TARGET_POLICY_PRIORITY_OVER_POST_CLAIM:-0}"
LEARNED_LOCAL_TARGET_POLICY_OUTCOME_RERANK="${LEARNED_LOCAL_TARGET_POLICY_OUTCOME_RERANK:-inherit}"
LEARNED_LOCAL_TARGET_POLICY_RERANK_POLICY_WEIGHT="${LEARNED_LOCAL_TARGET_POLICY_RERANK_POLICY_WEIGHT:-}"
ROUND_NAME="${ROUND_NAME:-dagger_round1}"
MODE="${MODE:-kinematic}"
SPLIT="${SPLIT:-train}"
DEVICE="${DEVICE:-cpu}"
POLICY_DEVICE="${POLICY_DEVICE:-cpu}"
MAX_TICKS="${MAX_TICKS:-700}"
POLICY_STATES="${POLICY_STATES:-EXPLORE,SEEK,SERVO}"
POLICY_POST_CLAIM_STATES="${POLICY_POST_CLAIM_STATES:-}"
LEARNED_LOCAL_DATASET_STATES="${LEARNED_LOCAL_DATASET_STATES:-}"
LEARNED_LOCAL_DATASET_MIN_CLAIMED_COUNT="${LEARNED_LOCAL_DATASET_MIN_CLAIMED_COUNT:-0}"
WEAK_MEMORY_SEEK_AREA_LOGIT="${WEAK_MEMORY_SEEK_AREA_LOGIT:-1.2}"
WEAK_MEMORY_SEEK_COLORS="${WEAK_MEMORY_SEEK_COLORS:-}"
WEAK_MEMORY_SEEK_STALL_STREAK="${WEAK_MEMORY_SEEK_STALL_STREAK:-2}"
WEAK_MEMORY_SEEK_YAW_LOOP_STREAK="${WEAK_MEMORY_SEEK_YAW_LOOP_STREAK:-0}"
WEAK_MEMORY_SEEK_YAW_LOOP_MAX_DISPLACEMENT_M="${WEAK_MEMORY_SEEK_YAW_LOOP_MAX_DISPLACEMENT_M:-0.01}"
WEAK_MEMORY_SEEK_EXPLORE_COOLDOWN_TICKS="${WEAK_MEMORY_SEEK_EXPLORE_COOLDOWN_TICKS:-36}"
WEAK_MEMORY_SEEK_FORCE_EXPLORE_ON_RECOVERY="${WEAK_MEMORY_SEEK_FORCE_EXPLORE_ON_RECOVERY:-0}"
SUCCESS_DIST_M="${SUCCESS_DIST_M:-1.2}"
CLAIM_NEAR_AREA_LOGIT="${CLAIM_NEAR_AREA_LOGIT:-2.6}"
CLAIM_NEAR_AREA_LOGIT_BY_COLOR="${CLAIM_NEAR_AREA_LOGIT_BY_COLOR:-yellow:2.45,green:2.45}"
CLAIM_NEAR_BEARING="${CLAIM_NEAR_BEARING:-0.32}"
EXPLORE_YAW_BEARING_THRESHOLD="${EXPLORE_YAW_BEARING_THRESHOLD:-0.5}"
EXPLORE_FORWARD_BEARING_THRESHOLD="${EXPLORE_FORWARD_BEARING_THRESHOLD:-0.18}"
POLICY_TRANSLATION_PRESSURE_AFTER="${POLICY_TRANSLATION_PRESSURE_AFTER:-8}"
POLICY_TRANSLATION_PRESSURE_MAX_BLOCKED_PROB="${POLICY_TRANSLATION_PRESSURE_MAX_BLOCKED_PROB:-1.01}"
POLICY_TRANSLATION_PRESSURE_MIN_PROGRESS_M="${POLICY_TRANSLATION_PRESSURE_MIN_PROGRESS_M:-0.02}"
POLICY_TRANSLATION_PRESSURE_PRIMITIVES="${POLICY_TRANSLATION_PRESSURE_PRIMITIVES:-forward_medium,arc_left,arc_right,forward_fast,backward}"
POLICY_TRANSLATION_PRESSURE_STATES="${POLICY_TRANSLATION_PRESSURE_STATES:-}"
LEARNED_LOCAL_ONLINE_MAP_SIZE="${LEARNED_LOCAL_ONLINE_MAP_SIZE:-21}"
LEARNED_LOCAL_ONLINE_MAP_CELL_M="${LEARNED_LOCAL_ONLINE_MAP_CELL_M:-0.45}"
LEARNED_LOCAL_VISUAL_READOUT_FEATURES="${LEARNED_LOCAL_VISUAL_READOUT_FEATURES:-0}"
EXPLORE_CLEAR_VISITED_ON_CLAIM="${EXPLORE_CLEAR_VISITED_ON_CLAIM:-1}"
LEARNED_LOCAL_ONLINE_MAP_HARD_GUARD_BLOCKS="${LEARNED_LOCAL_ONLINE_MAP_HARD_GUARD_BLOCKS:-0}"
LEARNED_LOCAL_ONLINE_MAP_ROUTE_REPLAY_GUARD_OVERRIDE="${LEARNED_LOCAL_ONLINE_MAP_ROUTE_REPLAY_GUARD_OVERRIDE:-0}"
LEARNED_LOCAL_ONLINE_MAP_LOW_PROGRESS_BLOCK_M="${LEARNED_LOCAL_ONLINE_MAP_LOW_PROGRESS_BLOCK_M:-0.0}"
POLICY_FRONTIER_PRESSURE_AFTER="${POLICY_FRONTIER_PRESSURE_AFTER:-1}"
POLICY_FRONTIER_PRESSURE_MAX_BLOCKED_PROB="${POLICY_FRONTIER_PRESSURE_MAX_BLOCKED_PROB:-1.01}"
POLICY_FRONTIER_PRESSURE_MIN_PROGRESS_M="${POLICY_FRONTIER_PRESSURE_MIN_PROGRESS_M:-0.02}"
POLICY_FRONTIER_PRESSURE_MIN_ROUTE_CELLS="${POLICY_FRONTIER_PRESSURE_MIN_ROUTE_CELLS:-0}"
POLICY_FRONTIER_PRESSURE_GUARD_BLOCKED_PENALTY="${POLICY_FRONTIER_PRESSURE_GUARD_BLOCKED_PENALTY:-1.0}"
POLICY_FRONTIER_PRESSURE_NONROUTE_BACKWARD_CLAIM_ESCAPE="${POLICY_FRONTIER_PRESSURE_NONROUTE_BACKWARD_CLAIM_ESCAPE:-0}"
POLICY_FRONTIER_PRESSURE_PREFER_UNGUARDED="${POLICY_FRONTIER_PRESSURE_PREFER_UNGUARDED:-0}"
POLICY_FRONTIER_PRESSURE_MAP_BLOCKED_BACKWARD_CLAIM_ESCAPE="${POLICY_FRONTIER_PRESSURE_MAP_BLOCKED_BACKWARD_CLAIM_ESCAPE:-0}"
POLICY_FRONTIER_PRESSURE_COMMIT="${POLICY_FRONTIER_PRESSURE_COMMIT:-0}"
POLICY_FRONTIER_PRESSURE_STATES="${POLICY_FRONTIER_PRESSURE_STATES:-}"
POLICY_ONLINE_MAP_NOVELTY_WEIGHT="${POLICY_ONLINE_MAP_NOVELTY_WEIGHT:-1.2}"
POLICY_ONLINE_MAP_CLAIM_REPULSION_WEIGHT="${POLICY_ONLINE_MAP_CLAIM_REPULSION_WEIGHT:-1.2}"
POLICY_ONLINE_MAP_FRONTIER_ROUTE_WEIGHT="${POLICY_ONLINE_MAP_FRONTIER_ROUTE_WEIGHT:-2.0}"
PRIMITIVE_OUTCOME_CHECKPOINT="${PRIMITIVE_OUTCOME_CHECKPOINT:-$ROOT/.generated/go2_wallaware_learned/primitive_outcome_jepa_mixed_progress08.pt}"
PRIMITIVE_OUTCOME_PRESERVE_ARC_REQUESTS="${PRIMITIVE_OUTCOME_PRESERVE_ARC_REQUESTS:-0}"
PRIMITIVE_OUTCOME_PRESERVE_TURN_UNTIL_FIRST_CLAIM="${PRIMITIVE_OUTCOME_PRESERVE_TURN_UNTIL_FIRST_CLAIM:-0}"
PRIMITIVE_OUTCOME_BLOCKED_HARD_VETO="${PRIMITIVE_OUTCOME_BLOCKED_HARD_VETO:-1}"
PRIMITIVE_OUTCOME_BLOCKED_HARD_VETO_AFTER_FIRST_CLAIM="${PRIMITIVE_OUTCOME_BLOCKED_HARD_VETO_AFTER_FIRST_CLAIM:-1}"
PRIMITIVE_OUTCOME_BLOCKED_HARD_VETO_SELECTED_PRIMITIVES="${PRIMITIVE_OUTCOME_BLOCKED_HARD_VETO_SELECTED_PRIMITIVES:-}"
WALL_GUARD_STATES="${WALL_GUARD_STATES:-EXPLORE}"
WALL_GUARD_POST_CLAIM_STATES="${WALL_GUARD_POST_CLAIM_STATES:-}"
WALL_GUARD_POST_CLAIM_MIN_CLAIMS="${WALL_GUARD_POST_CLAIM_MIN_CLAIMS:-1}"
PRIMITIVE_CLEARANCE_CHECKPOINT="${PRIMITIVE_CLEARANCE_CHECKPOINT:-}"
PRIMITIVE_CLEARANCE_THRESHOLD="${PRIMITIVE_CLEARANCE_THRESHOLD:-}"
BODY_CLEARANCE_TARGET_AREA_LOGIT="${BODY_CLEARANCE_TARGET_AREA_LOGIT:-1.2}"
BODY_CLEARANCE_LEARNED_PROB_FLOOR="${BODY_CLEARANCE_LEARNED_PROB_FLOOR:-0.35}"
BODY_CLEARANCE_LEARNED_PROB_WEIGHT="${BODY_CLEARANCE_LEARNED_PROB_WEIGHT:-1.0}"
BODY_CLEARANCE_NEAR_FORWARD_PROB_FLOOR="${BODY_CLEARANCE_NEAR_FORWARD_PROB_FLOOR:-}"
BODY_CLEARANCE_NEAR_FORWARD_PROB_WEIGHT="${BODY_CLEARANCE_NEAR_FORWARD_PROB_WEIGHT:-}"
BODY_CLEARANCE_NEAR_YAW_PROB_FLOOR="${BODY_CLEARANCE_NEAR_YAW_PROB_FLOOR:-}"
BODY_CLEARANCE_NEAR_YAW_PROB_WEIGHT="${BODY_CLEARANCE_NEAR_YAW_PROB_WEIGHT:-0.0}"
BODY_CLEARANCE_YAW_ALWAYS="${BODY_CLEARANCE_YAW_ALWAYS:-0}"
BODY_CLEARANCE_HARD_VETO_PROB="${BODY_CLEARANCE_HARD_VETO_PROB:-1.01}"
BODY_CLEARANCE_HARD_VETO_MARGIN="${BODY_CLEARANCE_HARD_VETO_MARGIN:-0.05}"
BODY_CLEARANCE_HARD_VETO_PRIMITIVES="${BODY_CLEARANCE_HARD_VETO_PRIMITIVES:-yaw_left,yaw_right,backward,hold}"
BODY_CLEARANCE_HARD_VETO_SELECTED_PRIMITIVES="${BODY_CLEARANCE_HARD_VETO_SELECTED_PRIMITIVES:-}"
BODY_CLEARANCE_SATURATED_VETO_PROB="${BODY_CLEARANCE_SATURATED_VETO_PROB:-1.01}"
BODY_CLEARANCE_SATURATED_VETO_SPREAD="${BODY_CLEARANCE_SATURATED_VETO_SPREAD:-0.01}"
BODY_CLEARANCE_SATURATED_VETO_PRIMITIVES="${BODY_CLEARANCE_SATURATED_VETO_PRIMITIVES:-yaw_left,yaw_right,backward,hold}"
BODY_CLEARANCE_SATURATED_VETO_SELECTED_PRIMITIVES="${BODY_CLEARANCE_SATURATED_VETO_SELECTED_PRIMITIVES:-arc_left,arc_right}"
BODY_CLEARANCE_YAW_DIRECTION_VETO_PROB="${BODY_CLEARANCE_YAW_DIRECTION_VETO_PROB:-1.01}"
BODY_CLEARANCE_YAW_DIRECTION_VETO_MARGIN="${BODY_CLEARANCE_YAW_DIRECTION_VETO_MARGIN:-0.05}"
BODY_CLEARANCE_RISK_ESCAPE_THRESHOLD="${BODY_CLEARANCE_RISK_ESCAPE_THRESHOLD:-1.01}"
BODY_CLEARANCE_RISK_ESCAPE_BLOCKS="${BODY_CLEARANCE_RISK_ESCAPE_BLOCKS:-0}"
BODY_CLEARANCE_RISK_ESCAPE_COOLDOWN_TICKS="${BODY_CLEARANCE_RISK_ESCAPE_COOLDOWN_TICKS:-0}"
BODY_CLEARANCE_RISK_ESCAPE_STATES="${BODY_CLEARANCE_RISK_ESCAPE_STATES:-EXPLORE,SEEK,SERVO}"
TARGET_COLORS="${TARGET_COLORS:-red,yellow,blue,green}"
TARGET_SWITCH_POLICY="${TARGET_SWITCH_POLICY:-${EVAL_TARGET_SWITCH_POLICY:-fixed}}"
TARGET_SWITCH_CONF="${TARGET_SWITCH_CONF:-0.8}"
TARGET_SWITCH_AREA_LOGIT="${TARGET_SWITCH_AREA_LOGIT:-${EVAL_TARGET_SWITCH_AREA_LOGIT:-0.0}}"
TARGET_SEEN_SWITCH_MIN_AREA_LOGIT="${TARGET_SEEN_SWITCH_MIN_AREA_LOGIT:-}"
ORACLE_STANDOFF_LABEL_STATES="${ORACLE_STANDOFF_LABEL_STATES:-EXPLORE}"
ORACLE_STANDOFF_ALLOW_ARCS="${ORACLE_STANDOFF_ALLOW_ARCS:-0}"
ORACLE_STANDOFF_ARC_MIN_BEARING="${ORACLE_STANDOFF_ARC_MIN_BEARING:-}"
ORACLE_STANDOFF_ARC_MAX_BEARING="${ORACLE_STANDOFF_ARC_MAX_BEARING:-}"
ORACLE_STANDOFF_ARC_MIN_TARGET_DIST_M="${ORACLE_STANDOFF_ARC_MIN_TARGET_DIST_M:-0.0}"
ORACLE_STANDOFF_HEADING_MODE="${ORACLE_STANDOFF_HEADING_MODE:-target}"
ORACLE_STANDOFF_HEADING_LOOKAHEAD_M="${ORACLE_STANDOFF_HEADING_LOOKAHEAD_M:-0.35}"
ORACLE_STANDOFF_LOOKAHEAD_M="${ORACLE_STANDOFF_LOOKAHEAD_M:-0.55}"
ORACLE_STANDOFF_PATH_SPACING_M="${ORACLE_STANDOFF_PATH_SPACING_M:-0.30}"
ORACLE_STANDOFF_CLEARANCE_WEIGHT="${ORACLE_STANDOFF_CLEARANCE_WEIGHT:-0.0}"
ORACLE_STANDOFF_CLEARANCE_TARGET_M="${ORACLE_STANDOFF_CLEARANCE_TARGET_M:-0.0}"
ORACLE_STANDOFF_CANDIDATES="${ORACLE_STANDOFF_CANDIDATES:-16}"
ORACLE_STANDOFF_ARRIVAL_M="${ORACLE_STANDOFF_ARRIVAL_M:-0.45}"
ORACLE_STANDOFF_BODY_CHECK="${ORACLE_STANDOFF_BODY_CHECK:-0}"
ORACLE_STANDOFF_BODY_LOOKAHEAD_M="${ORACLE_STANDOFF_BODY_LOOKAHEAD_M:-0.30}"
ORACLE_STANDOFF_BODY_MIN_CLEARANCE_M="${ORACLE_STANDOFF_BODY_MIN_CLEARANCE_M:--0.02}"
ORACLE_STANDOFF_BODY_RECOVERY_CLEARANCE_M="${ORACLE_STANDOFF_BODY_RECOVERY_CLEARANCE_M:-}"
TRAIN_SCENES="${TRAIN_SCENES:-medium_enclosed_maze_01732aabc542}"

mkdir -p "$OUT_DIR"
IFS=',' read -r -a TRAIN_SCENE_ARRAY <<< "$TRAIN_SCENES"

TRANSLATION_PRESSURE_EXTRA_ARGS=()
if [[ -n "$POLICY_TRANSLATION_PRESSURE_STATES" ]]; then
  TRANSLATION_PRESSURE_EXTRA_ARGS+=(--learned-local-policy-translation-pressure-states "$POLICY_TRANSLATION_PRESSURE_STATES")
fi

MULTI_TARGET_EXTRA_ARGS=()
if [[ -n "$TARGET_SEEN_SWITCH_MIN_AREA_LOGIT" ]]; then
  MULTI_TARGET_EXTRA_ARGS+=(--multi-target-seen-switch-min-area-logit "$TARGET_SEEN_SWITCH_MIN_AREA_LOGIT")
fi

FRONTIER_PRESSURE_EXTRA_ARGS=()
if [[ "$POLICY_FRONTIER_PRESSURE_NONROUTE_BACKWARD_CLAIM_ESCAPE" == "1" || "$POLICY_FRONTIER_PRESSURE_NONROUTE_BACKWARD_CLAIM_ESCAPE" == "true" ]]; then
  FRONTIER_PRESSURE_EXTRA_ARGS+=(--learned-local-policy-frontier-pressure-nonroute-backward-claim-escape)
fi
if [[ "$POLICY_FRONTIER_PRESSURE_PREFER_UNGUARDED" == "1" || "$POLICY_FRONTIER_PRESSURE_PREFER_UNGUARDED" == "true" ]]; then
  FRONTIER_PRESSURE_EXTRA_ARGS+=(--learned-local-policy-frontier-pressure-prefer-unguarded)
fi
if [[ "$POLICY_FRONTIER_PRESSURE_MAP_BLOCKED_BACKWARD_CLAIM_ESCAPE" == "1" || "$POLICY_FRONTIER_PRESSURE_MAP_BLOCKED_BACKWARD_CLAIM_ESCAPE" == "true" ]]; then
  FRONTIER_PRESSURE_EXTRA_ARGS+=(--learned-local-policy-frontier-pressure-map-blocked-backward-claim-escape)
fi
if [[ "${POLICY_FRONTIER_PRESSURE_GUARDED_RETRY_AFTER_NOOPS:-0}" != "0" ]]; then
  FRONTIER_PRESSURE_EXTRA_ARGS+=(--learned-local-policy-frontier-pressure-guarded-retry-after-noops "${POLICY_FRONTIER_PRESSURE_GUARDED_RETRY_AFTER_NOOPS:-0}")
fi
if [[ "$POLICY_FRONTIER_PRESSURE_COMMIT" == "1" || "$POLICY_FRONTIER_PRESSURE_COMMIT" == "true" ]]; then
  FRONTIER_PRESSURE_EXTRA_ARGS+=(--learned-local-policy-frontier-pressure-commit)
fi
if [[ -n "$POLICY_FRONTIER_PRESSURE_STATES" ]]; then
  FRONTIER_PRESSURE_EXTRA_ARGS+=(--learned-local-policy-frontier-pressure-states "$POLICY_FRONTIER_PRESSURE_STATES")
fi

ONLINE_MAP_EXTRA_ARGS=()
if [[ "$EXPLORE_CLEAR_VISITED_ON_CLAIM" == "1" || "$EXPLORE_CLEAR_VISITED_ON_CLAIM" == "true" ]]; then
  ONLINE_MAP_EXTRA_ARGS+=(--explore-clear-visited-on-claim)
fi
if [[ "$LEARNED_LOCAL_ONLINE_MAP_ROUTE_REPLAY_GUARD_OVERRIDE" == "1" || "$LEARNED_LOCAL_ONLINE_MAP_ROUTE_REPLAY_GUARD_OVERRIDE" == "true" ]]; then
  ONLINE_MAP_EXTRA_ARGS+=(--learned-local-online-map-route-replay-guard-override)
fi
if [[ "$LEARNED_LOCAL_ONLINE_MAP_HARD_GUARD_BLOCKS" == "1" || "$LEARNED_LOCAL_ONLINE_MAP_HARD_GUARD_BLOCKS" == "true" ]]; then
  ONLINE_MAP_EXTRA_ARGS+=(--learned-local-online-map-hard-guard-blocks)
fi
if [[ "$LEARNED_LOCAL_ONLINE_MAP_LOW_PROGRESS_BLOCK_M" != "0" && "$LEARNED_LOCAL_ONLINE_MAP_LOW_PROGRESS_BLOCK_M" != "0.0" ]]; then
  ONLINE_MAP_EXTRA_ARGS+=(--learned-local-online-map-low-progress-block-m "$LEARNED_LOCAL_ONLINE_MAP_LOW_PROGRESS_BLOCK_M")
fi
if [[ "$WEAK_MEMORY_SEEK_FORCE_EXPLORE_ON_RECOVERY" == "1" || "$WEAK_MEMORY_SEEK_FORCE_EXPLORE_ON_RECOVERY" == "true" ]]; then
  ONLINE_MAP_EXTRA_ARGS+=(--weak-memory-seek-force-explore-on-recovery)
fi
if [[ -n "$WEAK_MEMORY_SEEK_COLORS" ]]; then
  ONLINE_MAP_EXTRA_ARGS+=(--weak-memory-seek-colors "$WEAK_MEMORY_SEEK_COLORS")
fi
if [[ "$WEAK_MEMORY_SEEK_YAW_LOOP_STREAK" != "0" ]]; then
  ONLINE_MAP_EXTRA_ARGS+=(--weak-memory-seek-yaw-loop-streak "$WEAK_MEMORY_SEEK_YAW_LOOP_STREAK")
  ONLINE_MAP_EXTRA_ARGS+=(--weak-memory-seek-yaw-loop-max-displacement-m "$WEAK_MEMORY_SEEK_YAW_LOOP_MAX_DISPLACEMENT_M")
fi

LEARNED_LOCAL_FEATURE_ARGS=(
  --learned-local-clock-features
  --learned-local-state-features
  --learned-local-online-map-features
)
if [[ "$LEARNED_LOCAL_VISUAL_READOUT_FEATURES" == "1" || "$LEARNED_LOCAL_VISUAL_READOUT_FEATURES" == "true" ]]; then
  LEARNED_LOCAL_FEATURE_ARGS+=(--learned-local-visual-readout-features)
fi

PRIMITIVE_OUTCOME_RUNTIME_ARGS=()
if [[ "$PRIMITIVE_OUTCOME_PRESERVE_ARC_REQUESTS" == "1" || "$PRIMITIVE_OUTCOME_PRESERVE_ARC_REQUESTS" == "true" ]]; then
  PRIMITIVE_OUTCOME_RUNTIME_ARGS+=(--primitive-outcome-preserve-arc-requests)
fi
if [[ "$PRIMITIVE_OUTCOME_PRESERVE_TURN_UNTIL_FIRST_CLAIM" == "1" || "$PRIMITIVE_OUTCOME_PRESERVE_TURN_UNTIL_FIRST_CLAIM" == "true" ]]; then
  PRIMITIVE_OUTCOME_RUNTIME_ARGS+=(--primitive-outcome-preserve-turn-until-first-claim)
fi
if [[ "$PRIMITIVE_OUTCOME_BLOCKED_HARD_VETO" == "1" || "$PRIMITIVE_OUTCOME_BLOCKED_HARD_VETO" == "true" ]]; then
  PRIMITIVE_OUTCOME_RUNTIME_ARGS+=(--primitive-outcome-blocked-hard-veto)
fi
if [[ "$PRIMITIVE_OUTCOME_BLOCKED_HARD_VETO_AFTER_FIRST_CLAIM" == "1" || "$PRIMITIVE_OUTCOME_BLOCKED_HARD_VETO_AFTER_FIRST_CLAIM" == "true" ]]; then
  PRIMITIVE_OUTCOME_RUNTIME_ARGS+=(--primitive-outcome-blocked-hard-veto-after-first-claim)
fi
if [[ -n "$PRIMITIVE_OUTCOME_BLOCKED_HARD_VETO_SELECTED_PRIMITIVES" ]]; then
  PRIMITIVE_OUTCOME_RUNTIME_ARGS+=(--primitive-outcome-blocked-hard-veto-selected-primitives "$PRIMITIVE_OUTCOME_BLOCKED_HARD_VETO_SELECTED_PRIMITIVES")
fi

PRIMITIVE_CLEARANCE_ARGS=()
if [[ -n "$PRIMITIVE_CLEARANCE_CHECKPOINT" ]]; then
  PRIMITIVE_CLEARANCE_ARGS+=(--primitive-clearance-checkpoint "$PRIMITIVE_CLEARANCE_CHECKPOINT")
fi
if [[ -n "$PRIMITIVE_CLEARANCE_THRESHOLD" ]]; then
  PRIMITIVE_CLEARANCE_ARGS+=(--primitive-clearance-threshold "$PRIMITIVE_CLEARANCE_THRESHOLD")
fi
if [[ -n "$BODY_CLEARANCE_NEAR_FORWARD_PROB_FLOOR" ]]; then
  PRIMITIVE_CLEARANCE_ARGS+=(--body-clearance-near-forward-prob-floor "$BODY_CLEARANCE_NEAR_FORWARD_PROB_FLOOR")
fi
if [[ -n "$BODY_CLEARANCE_NEAR_FORWARD_PROB_WEIGHT" ]]; then
  PRIMITIVE_CLEARANCE_ARGS+=(--body-clearance-near-forward-prob-weight "$BODY_CLEARANCE_NEAR_FORWARD_PROB_WEIGHT")
fi
if [[ -n "$BODY_CLEARANCE_NEAR_YAW_PROB_FLOOR" ]]; then
  PRIMITIVE_CLEARANCE_ARGS+=(--body-clearance-near-yaw-prob-floor "$BODY_CLEARANCE_NEAR_YAW_PROB_FLOOR")
fi
if [[ "$BODY_CLEARANCE_YAW_ALWAYS" == "1" || "$BODY_CLEARANCE_YAW_ALWAYS" == "true" ]]; then
  PRIMITIVE_CLEARANCE_ARGS+=(--body-clearance-yaw-always)
fi
PRIMITIVE_CLEARANCE_ARGS+=(
  --body-clearance-learned-prob-floor "$BODY_CLEARANCE_LEARNED_PROB_FLOOR"
  --body-clearance-learned-prob-weight "$BODY_CLEARANCE_LEARNED_PROB_WEIGHT"
  --body-clearance-near-yaw-prob-weight "$BODY_CLEARANCE_NEAR_YAW_PROB_WEIGHT"
  --body-clearance-hard-veto-prob "$BODY_CLEARANCE_HARD_VETO_PROB"
  --body-clearance-hard-veto-margin "$BODY_CLEARANCE_HARD_VETO_MARGIN"
  --body-clearance-hard-veto-primitives "$BODY_CLEARANCE_HARD_VETO_PRIMITIVES"
  --body-clearance-saturated-veto-prob "$BODY_CLEARANCE_SATURATED_VETO_PROB"
  --body-clearance-saturated-veto-spread "$BODY_CLEARANCE_SATURATED_VETO_SPREAD"
  --body-clearance-saturated-veto-primitives "$BODY_CLEARANCE_SATURATED_VETO_PRIMITIVES"
  --body-clearance-saturated-veto-selected-primitives "$BODY_CLEARANCE_SATURATED_VETO_SELECTED_PRIMITIVES"
  --body-clearance-yaw-direction-veto-prob "$BODY_CLEARANCE_YAW_DIRECTION_VETO_PROB"
  --body-clearance-yaw-direction-veto-margin "$BODY_CLEARANCE_YAW_DIRECTION_VETO_MARGIN"
  --body-clearance-risk-escape-threshold "$BODY_CLEARANCE_RISK_ESCAPE_THRESHOLD"
  --body-clearance-risk-escape-blocks "$BODY_CLEARANCE_RISK_ESCAPE_BLOCKS"
  --body-clearance-risk-escape-cooldown-ticks "$BODY_CLEARANCE_RISK_ESCAPE_COOLDOWN_TICKS"
  --body-clearance-risk-escape-states "$BODY_CLEARANCE_RISK_ESCAPE_STATES"
)
if [[ -n "$BODY_CLEARANCE_HARD_VETO_SELECTED_PRIMITIVES" ]]; then
  PRIMITIVE_CLEARANCE_ARGS+=(--body-clearance-hard-veto-selected-primitives "$BODY_CLEARANCE_HARD_VETO_SELECTED_PRIMITIVES")
fi

LEARNED_LOCAL_DATASET_STATE_ARGS=()
if [[ -n "$LEARNED_LOCAL_DATASET_STATES" ]]; then
  LEARNED_LOCAL_DATASET_STATE_ARGS=(
    --learned-local-dataset-states "$LEARNED_LOCAL_DATASET_STATES"
  )
fi

POST_CLAIM_POLICY_ARGS=()
if [[ -n "$POST_CLAIM_POLICY" ]]; then
  POST_CLAIM_POLICY_ARGS=(
    --learned-local-post-claim-policy-checkpoint "$POST_CLAIM_POLICY"
    --learned-local-post-claim-policy-outcome-rerank "$POST_CLAIM_POLICY_OUTCOME_RERANK"
  )
fi

TARGET_POLICY_ARGS=()
if [[ -n "$LEARNED_LOCAL_TARGET_POLICY_CHECKPOINTS" ]]; then
  TARGET_POLICY_ARGS=(
    --learned-local-target-policy-checkpoints "$LEARNED_LOCAL_TARGET_POLICY_CHECKPOINTS"
  )
fi
if [[ -n "$LEARNED_LOCAL_TARGET_POLICY_STATE_CHECKPOINTS" ]]; then
  TARGET_POLICY_ARGS+=(
    --learned-local-target-policy-state-checkpoints "$LEARNED_LOCAL_TARGET_POLICY_STATE_CHECKPOINTS"
  )
fi
if [[ -n "$LEARNED_LOCAL_TARGET_POLICY_CHECKPOINTS" || -n "$LEARNED_LOCAL_TARGET_POLICY_STATE_CHECKPOINTS" ]]; then
  TARGET_POLICY_ARGS+=(
    --learned-local-target-policy-outcome-rerank "$LEARNED_LOCAL_TARGET_POLICY_OUTCOME_RERANK"
  )
  if [[ "$LEARNED_LOCAL_TARGET_POLICY_PRIORITY_OVER_POST_CLAIM" == "1" || "$LEARNED_LOCAL_TARGET_POLICY_PRIORITY_OVER_POST_CLAIM" == "true" ]]; then
    TARGET_POLICY_ARGS+=(--learned-local-target-policy-priority-over-post-claim)
  fi
  if [[ -n "$LEARNED_LOCAL_TARGET_POLICY_RERANK_POLICY_WEIGHT" ]]; then
    TARGET_POLICY_ARGS+=(
      --learned-local-target-policy-rerank-policy-weight "$LEARNED_LOCAL_TARGET_POLICY_RERANK_POLICY_WEIGHT"
    )
  fi
fi

ORACLE_STANDOFF_ARGS=(
  --explore-standoff-lookahead-m "$ORACLE_STANDOFF_LOOKAHEAD_M"
  --explore-standoff-path-spacing-m "$ORACLE_STANDOFF_PATH_SPACING_M"
  --explore-standoff-clearance-weight "$ORACLE_STANDOFF_CLEARANCE_WEIGHT"
  --explore-standoff-clearance-target-m "$ORACLE_STANDOFF_CLEARANCE_TARGET_M"
  --explore-standoff-candidates "$ORACLE_STANDOFF_CANDIDATES"
  --explore-standoff-arrival-m "$ORACLE_STANDOFF_ARRIVAL_M"
  --explore-standoff-arc-min-target-dist-m "$ORACLE_STANDOFF_ARC_MIN_TARGET_DIST_M"
  --explore-standoff-heading-mode "$ORACLE_STANDOFF_HEADING_MODE"
  --explore-standoff-heading-lookahead-m "$ORACLE_STANDOFF_HEADING_LOOKAHEAD_M"
  --explore-standoff-body-lookahead-m "$ORACLE_STANDOFF_BODY_LOOKAHEAD_M"
  --explore-standoff-body-min-clearance-m "$ORACLE_STANDOFF_BODY_MIN_CLEARANCE_M"
)
if [[ "$ORACLE_STANDOFF_ALLOW_ARCS" == "1" || "$ORACLE_STANDOFF_ALLOW_ARCS" == "true" ]]; then
  ORACLE_STANDOFF_ARGS+=(--explore-standoff-allow-arcs)
fi
if [[ -n "$ORACLE_STANDOFF_ARC_MIN_BEARING" ]]; then
  ORACLE_STANDOFF_ARGS+=(--explore-standoff-arc-min-bearing "$ORACLE_STANDOFF_ARC_MIN_BEARING")
fi
if [[ -n "$ORACLE_STANDOFF_ARC_MAX_BEARING" ]]; then
  ORACLE_STANDOFF_ARGS+=(--explore-standoff-arc-max-bearing "$ORACLE_STANDOFF_ARC_MAX_BEARING")
fi
if [[ "$ORACLE_STANDOFF_BODY_CHECK" == "1" || "$ORACLE_STANDOFF_BODY_CHECK" == "true" ]]; then
  ORACLE_STANDOFF_ARGS+=(--explore-standoff-body-check)
fi
if [[ -n "$ORACLE_STANDOFF_BODY_RECOVERY_CLEARANCE_M" ]]; then
  ORACLE_STANDOFF_ARGS+=(
    --explore-standoff-body-recovery-clearance-m "$ORACLE_STANDOFF_BODY_RECOVERY_CLEARANCE_M"
  )
fi

COMMON_ARGS=(
  --policy memory
  --demo-mode explore
  --target-color all
  --target-colors "$TARGET_COLORS"
  --controller "$ROOT/.generated/go2_hidden_target_memory/go2_rgb_jepa_strict_exact_valuenorm_gate_neg6_pair8_nonforward_eval_seed20260825_h512.pt"
  --frozen-jepa-checkpoint "$ROOT/.generated/go2_hidden_target_memory/go2_jepa_latent_encoder_medium_hidden_claim_seed20260628_img64_lat96_contrast02.pt"
  --primitive-outcome-checkpoint "$PRIMITIVE_OUTCOME_CHECKPOINT"
  "${PRIMITIVE_CLEARANCE_ARGS[@]}"
  --wall-aware-planner
  --wall-decision-source learned_action
  --wall-guard-states "$WALL_GUARD_STATES"
  --wall-guard-post-claim-states "$WALL_GUARD_POST_CLAIM_STATES"
  --wall-guard-post-claim-min-claims "$WALL_GUARD_POST_CLAIM_MIN_CLAIMS"
  --success-dist-m "$SUCCESS_DIST_M"
  --mask-area-threshold 0.01
  --claim-min-seen-ticks 18
  --claim-near-area-logit "$CLAIM_NEAR_AREA_LOGIT"
  --claim-near-area-logit-by-color "$CLAIM_NEAR_AREA_LOGIT_BY_COLOR"
  --claim-near-bearing "$CLAIM_NEAR_BEARING"
  --claim-near-min-seen-ticks 8
  --multi-target-switch-conf "$TARGET_SWITCH_CONF"
  --multi-target-switch-area-logit "$TARGET_SWITCH_AREA_LOGIT"
  "${MULTI_TARGET_EXTRA_ARGS[@]}"
  --wall-body-probe-margin-m 0.0
  --wall-predicted-blocked-waypoint-replan
  --wall-predicted-blocked-waypoint-streak 2
  --primitive-outcome-forward-progress-floor 0.04
  --primitive-outcome-progress-floor-min-blocked-prob 0.05
  --primitive-outcome-progress-floor-force-below 0.01
  --primitive-outcome-forward-progress-penalty 0.9
  --primitive-outcome-progress-floor-prefer-yaw
  --primitive-outcome-preserve-turn-requests
  --primitive-outcome-preserve-turn-states EXPLORE
  "${PRIMITIVE_OUTCOME_RUNTIME_ARGS[@]}"
  --body-clearance-target-servo
  --body-clearance-target-area-logit "$BODY_CLEARANCE_TARGET_AREA_LOGIT"
  --body-clearance-target-bearing 0.16
  --body-clearance-target-forward-primitive forward_medium
  --body-clearance-latch-ticks 8
  --body-clearance-learned-min-area-logit "$BODY_CLEARANCE_TARGET_AREA_LOGIT"
  --weak-memory-seek-area-logit "$WEAK_MEMORY_SEEK_AREA_LOGIT"
  --weak-memory-seek-stall-streak "$WEAK_MEMORY_SEEK_STALL_STREAK"
  --weak-memory-seek-explore-cooldown-ticks "$WEAK_MEMORY_SEEK_EXPLORE_COOLDOWN_TICKS"
  --explore-yaw-bearing-threshold "$EXPLORE_YAW_BEARING_THRESHOLD"
  --explore-forward-bearing-threshold "$EXPLORE_FORWARD_BEARING_THRESHOLD"
  --wall-stall-block-waypoint
  "${ORACLE_STANDOFF_ARGS[@]}"
  --explore-reset-on-claim
  "${ONLINE_MAP_EXTRA_ARGS[@]}"
)

for SCENE_ID in "${TRAIN_SCENE_ARRAY[@]}"; do
  RESULT="$OUT_DIR/${ROUND_NAME}_${SCENE_ID}_result.json"
  DATASET="$OUT_DIR/${ROUND_NAME}_${SCENE_ID}_clock_dataset.npz"
  "$PYTHON" "$ROOT/scripts/benchmark_go2_memory_closed_loop.py" \
    --mode "$MODE" \
    --policy-device "$POLICY_DEVICE" \
    --device "$DEVICE" \
    --split "$SPLIT" \
    --scene-id "$SCENE_ID" \
    --max-ticks "$MAX_TICKS" \
    "${COMMON_ARGS[@]}" \
    --multi-target-switch-policy "$TARGET_SWITCH_POLICY" \
    --explore-goal-policy learned_policy \
    --learned-local-policy-checkpoint "$POLICY" \
    --learned-local-policy-states "$POLICY_STATES" \
    --learned-local-policy-post-claim-states "$POLICY_POST_CLAIM_STATES" \
    "${POST_CLAIM_POLICY_ARGS[@]}" \
    "${TARGET_POLICY_ARGS[@]}" \
    "${LEARNED_LOCAL_DATASET_STATE_ARGS[@]}" \
    --learned-local-dataset-min-claimed-count "$LEARNED_LOCAL_DATASET_MIN_CLAIMED_COUNT" \
    --learned-local-online-map-size "$LEARNED_LOCAL_ONLINE_MAP_SIZE" \
    --learned-local-online-map-cell-m "$LEARNED_LOCAL_ONLINE_MAP_CELL_M" \
    --learned-local-policy-outcome-rerank \
    --learned-local-policy-rerank-top-k 5 \
    --learned-local-policy-rerank-policy-weight 0.2 \
    --learned-local-policy-rerank-blocked-weight 3.0 \
    --learned-local-policy-rerank-clearance-weight 0.5 \
    --learned-local-policy-rerank-progress-weight 1.0 \
    --learned-local-policy-rerank-hard-blocked-penalty 2.0 \
    --learned-local-policy-rerank-bearing-turn-threshold 0.4 \
    --learned-local-policy-rerank-bearing-turn-bonus 0.4 \
    --learned-local-policy-translation-pressure-after "$POLICY_TRANSLATION_PRESSURE_AFTER" \
    --learned-local-policy-translation-pressure-max-blocked-prob "$POLICY_TRANSLATION_PRESSURE_MAX_BLOCKED_PROB" \
    --learned-local-policy-translation-pressure-min-progress-m "$POLICY_TRANSLATION_PRESSURE_MIN_PROGRESS_M" \
    --learned-local-policy-translation-pressure-primitives "$POLICY_TRANSLATION_PRESSURE_PRIMITIVES" \
    "${TRANSLATION_PRESSURE_EXTRA_ARGS[@]}" \
    --learned-local-policy-frontier-pressure-after "$POLICY_FRONTIER_PRESSURE_AFTER" \
    --learned-local-policy-frontier-pressure-max-blocked-prob "$POLICY_FRONTIER_PRESSURE_MAX_BLOCKED_PROB" \
    --learned-local-policy-frontier-pressure-min-progress-m "$POLICY_FRONTIER_PRESSURE_MIN_PROGRESS_M" \
    --learned-local-policy-frontier-pressure-min-route-cells "$POLICY_FRONTIER_PRESSURE_MIN_ROUTE_CELLS" \
    --learned-local-policy-frontier-pressure-guard-blocked-penalty "$POLICY_FRONTIER_PRESSURE_GUARD_BLOCKED_PENALTY" \
    "${FRONTIER_PRESSURE_EXTRA_ARGS[@]}" \
    --learned-local-policy-online-map-novelty-weight "$POLICY_ONLINE_MAP_NOVELTY_WEIGHT" \
    --learned-local-policy-online-map-claim-repulsion-weight "$POLICY_ONLINE_MAP_CLAIM_REPULSION_WEIGHT" \
    --learned-local-policy-online-map-frontier-route-weight "$POLICY_ONLINE_MAP_FRONTIER_ROUTE_WEIGHT" \
    --learned-local-oracle-standoff-labels \
    --learned-local-oracle-standoff-label-states "$ORACLE_STANDOFF_LABEL_STATES" \
    "${LEARNED_LOCAL_FEATURE_ARGS[@]}" \
    --learned-local-dataset-output "$DATASET" \
    --output "$RESULT"
done
