"""Gap diagnosis, pipeline test and like-for-like scoring on fresh-check decisions.

Diagnosis on the check mazes only; validation and sealed sets are untouched. The inputs are
the logged decisions of the C3-v2 and C4-v2 fresh-check missions:
- frames regenerated by verified replay (`replay_go2_c3v2_check_frames_development.py`);
- command histories from the native policy histories;
- the candidate applied tapes from the model calls.

1. Pipeline test. The logged inputs are re-run through the offline acceptance evaluator's
   computation and compared with the logged run-time predictions.
   - C3-v2 missions: the C3-v2 readout on the frozen predictor's features for the selected
     candidate (and the executed one, if different) on every decision, and for all six
     candidates on every 20th decision.
   - C4-v2 missions: C4-v2 on all six candidates of every decision.
   - The C3 path is `pooled_features` with the encoder computed once per decision (its lines
     unchanged); the C4 path is the evaluator's, batched over the six candidates.
   - Any difference above TOLERANCE is a suspected correctness defect. The first divergence
     is recorded, and nothing further is interpreted.
2. Like-for-like. On the same decisions, C3-v1, C3-v2, C4-v1, C4-v2 and C1 are scored
   against true travel. C1 is the logged command-history forecast, which the harness computes
   for every candidate of every decision.
   - True travel: the physics-trace motion in the decision body frame, used only where the
     executed applied tape equals the scored candidate's tape.
   - Forward: the forward candidate on decisions where it was executed. Reported: the median
     predicted/true 800-ms translation ratio and the 800-ms XY error, split by from rest
     (zero applied commands in the preceding 1.0 s) and moving, with counts.
"""
from collections import defaultdict
import hashlib
import json
from pathlib import Path
import time

import numpy as np
import torch
from torch.nn import functional as F

from lewm import decision_headroom_json_v42_development as output
from lewm import navigation_capability_active_wall_development as wall
from lewm.c3v2_offline_pipeline_development import Recording
from lewm.dense_visual_motion_readout_development import pool_tokens
from lewm.navigation_capability_supervised_development import DirectMotionPredictor
from scripts import run_go2_navigation_capability_completed_support_v4_development as owner
from scripts import train_go2_all_motion_horizon_readout_development as previous

BASE = Path(json.loads(owner.PROTOCOL.read_text())['output_root'])
ROOT = BASE/'c3v2_gap_diagnosis_v1'
REPLAYS = ROOT/'replays'
ACTIONS = ('hold', 'forward', 'left_arc', 'right_arc', 'left_turn', 'right_turn')
FORWARD, TOLERANCE, ALL_SIX_STRIDE = 1, 1e-5, 20
PREREG = Path('docs/go2_navigation_capability_preregistration_v1_2026-09-25.json')


def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def load_models():
    model = owner.source.load_dense_navigation_model('action', readout_arm='maze_view_maze_data')
    readout_v2 = previous.prior.previous.load('mixed_data')
    readout_v2.load_state_dict(torch.load(BASE/'c3v2_readout_fit_v1/readout_v2_final.pt', map_location='cpu', weights_only=False)['model_state_dict'])
    readouts = dict(C3_v1=model.readout, C3_v2=readout_v2.cuda().eval().requires_grad_(False))
    head = torch.load(json.loads(PREREG.read_text())['controllers']['C3']['head_binding']['path'], map_location='cpu', weights_only=False)['model_state_dict']
    c4s = {}
    for name, path in (('C4_v1', BASE/'c4_fit_attempt002/direct_final.pt'), ('C4_v2', BASE/'c4v2_fit_v1/direct_v2_final.pt')):
        c4 = DirectMotionPredictor(head['target_mean'], head['target_scale'])
        c4.load_state_dict(torch.load(path, map_location='cpu', weights_only=False)['model_state_dict'])
        c4s[name] = c4.cuda().eval()
    return model, readouts, c4s


@torch.inference_mode()
def predict(model, readouts, c4s, native, tapes, c3_candidates):
    """Offline evaluator computation for one decision: C3 readouts on the listed candidates, C4 on all six."""
    device = next(model.predictor.parameters()).device
    context = F.layer_norm(model.encoder.tokens(native['pixels'].to(device)).float(), (1024,))[None]
    control = native['past_applied_commands'][:, [0, 2]].reshape(3, 5, 2).to(device)
    control = ((control-model.control_mean)/model.control_std)[None]
    current = pool_tokens(context[:, -1])
    mask = torch.ones(1, 768, dtype=torch.bool, device=device)
    out = {name: {} for name in list(readouts)+list(c4s)}
    for k in c3_candidates:
        actions = torch.from_numpy(np.asarray(tapes[k], np.float32)[None][:, :, [0, 2]]).to(device)
        predicted = {}
        for h in range(1, 9):
            o = model.predictor(context, actions, torch.full((1,), h, dtype=torch.long, device=device), mask, control=control)
            predicted[h] = pool_tokens(F.layer_norm(o.float(), (1024,)))
        for name, readout in readouts.items():
            out[name][k] = np.stack([readout(current, predicted[h]).float().cpu().numpy()[0] for h in range(1, 9)])
    feats = pool_tokens(context[0])[None].expand(48, -1, -1, -1)
    acts = torch.from_numpy(np.asarray(tapes, np.float32)[:, :, [0, 2]]).to(device).repeat_interleave(8, dim=0)
    horizons = torch.arange(1, 9, device=device).repeat(6)
    for name, c4 in c4s.items():
        motion = c4(feats, control.expand(48, -1, -1, -1), acts, horizons).float().cpu().numpy().reshape(6, 8, 3)
        out[name] = {k: motion[k] for k in range(6)}
    return out


def score_run(run, models, rows, divergences):
    arm = json.loads((run/'config.json').read_text())['controller']
    deployed = 'C3_v2' if arm == 'C3' else 'C4_v2'
    replay = REPLAYS/run.name
    while not (replay/'replay_verification.json').exists():  # a replay still running
        if (replay/'failure.json').exists():
            raise RuntimeError('replay failed: '+run.name)
        time.sleep(30)
    assert json.loads((replay/'replay_verification.json').read_text())['passed']
    n = run/'native'
    recording = Recording(n/'policy_histories.npz', n/'policy_observations.json', lambda i: replay/'ego_frames'/f'{i:04d}.png', n/'physics_trace.npz')
    meta = json.loads((n/'in_memory_camera_observations.json').read_text())['frames']
    plans = {r['measured_ns']: r for r in json.loads((run/'planning.json').read_text()) if 'selection' in r}
    worst = dict(xy=0., yaw=0., values=0)
    for index, call in enumerate(json.loads((run/'model_calls.json').read_text())):
        frame = (call['observed_ns']-1_500_000_000)//100_000_000
        plan = plans.get(call['observed_ns'])
        tapes = np.asarray(call['applied_commands'], np.float32)
        logged = np.asarray(call['motion_xy_yaw'], np.float32)
        executed = matched = truth = None
        if frame+8 < len(meta):
            try:
                executed = recording.executed_tape(frame)
                matched = [k for k in range(6) if np.array_equal(executed, tapes[k])]
                truth = recording.targets(frame, meta)
            except ValueError:
                pass
        selected = ACTIONS.index(plan['action']) if plan else None
        candidates = sorted(set(([selected] if selected is not None else []) + (matched or []))
                            | (set(range(6)) if index % ALL_SIX_STRIDE == 0 or selected is None else set()))
        needs_c3 = arm == 'C3' or (matched and FORWARD in matched)
        try:
            native = recording.native(frame)
        except ValueError as error:
            worst['context_unavailable_offline'] = worst.get('context_unavailable_offline', 0)+1
            if not divergences:
                divergences.append(dict(run=run.name, decision=index, observed_ns=call['observed_ns'], frame=int(frame),
                                        reason='offline native context could not be built for a logged decision: '+repr(error)))
            continue
        predictions = predict(*models, native, tapes, candidates if needs_c3 else [])
        for k, value in predictions[deployed].items():
            d = np.abs(value-logged[k])
            worst['xy'] = max(worst['xy'], float(d[:, :2].max()))
            yaw = np.abs(np.arctan2(np.sin(value[:, 2]-logged[k][:, 2]), np.cos(value[:, 2]-logged[k][:, 2])))
            worst['yaw'] = max(worst['yaw'], float(yaw.max()))
            worst['values'] += d.size
            if (d[:, :2].max() > TOLERANCE or yaw.max() > TOLERANCE) and not divergences:
                h = int(np.argmax(np.maximum(d[:, :2].max(axis=1), yaw)))
                divergences.append(dict(run=run.name, decision=index, observed_ns=call['observed_ns'], frame=int(frame), candidate=ACTIONS[k],
                                        horizon_ms=int(100*(h+1)), offline=value[h].tolist(), logged=logged[k][h].tolist()))
        if matched is not None and FORWARD in matched and truth is not None:
            c1 = np.asarray(plan['motion_correction']['command_history_forecast_xy_yaw'], np.float32)[FORWARD] if plan else None
            row = dict(run=run.name, source_arm=arm, frame=int(frame), from_rest=bool(not recording.values[frame][-10:].any()),
                       true_800_xy=truth[7, :2].tolist())
            for name in ('C3_v1', 'C3_v2', 'C4_v1', 'C4_v2'):
                row[name] = predictions[name][FORWARD][7, :2].tolist()
            row['C1'] = None if c1 is None else c1[7, :2].tolist()
            row['logged'] = logged[FORWARD][7, :2].tolist()
            rows.append(row)
        # Keep only the frames the next decisions can use.
        for key in [key for key in recording._pixels if key < frame-10]:
            del recording._pixels[key]
    return dict(run=run.name, arm=arm, deployed=deployed, decisions=index+1, max_abs_xy_m=worst['xy'], max_abs_yaw_rad=worst['yaw'],
                compared_values=worst['values'], context_unavailable_offline=worst.get('context_unavailable_offline', 0))


def summarise(rows):
    out = {}
    for split, keep in (('from_rest', lambda r: r['from_rest']), ('moving', lambda r: not r['from_rest']), ('all', lambda r: True)):
        subset = [r for r in rows if keep(r)]
        true = np.asarray([r['true_800_xy'] for r in subset]) if subset else np.zeros((0, 2))
        out[split] = dict(decisions=len(subset), by_source=dict(C3_missions=sum(r['source_arm'] == 'C3' for r in subset),
                                                                 C4_missions=sum(r['source_arm'] == 'C4' for r in subset)),
                          median_true_mm=float(np.median(np.linalg.norm(true, axis=1)))*1000 if subset else None)
        for name in ('C3_v1', 'C3_v2', 'C4_v1', 'C4_v2', 'C1'):
            usable = [r for r in subset if r[name] is not None and np.linalg.norm(r['true_800_xy']) > 0]
            if not usable:
                out[split][name] = None
                continue
            p = np.asarray([r[name] for r in usable])
            t = np.asarray([r['true_800_xy'] for r in usable])
            out[split][name] = dict(n=len(usable), median_ratio=float(np.median(np.linalg.norm(p, axis=1)/np.linalg.norm(t, axis=1))),
                                    median_predicted_mm=float(np.median(np.linalg.norm(p, axis=1)))*1000,
                                    median_xy_error_mm=float(np.median(np.linalg.norm(p-t, axis=1)))*1000,
                                    rmse_xy_mm=float(np.sqrt(np.mean(np.sum((p-t)**2, axis=1))))*1000)
    return out


def main(only, out):
    output.install(BASE)
    models = load_models()
    runs = [d for pattern in ('c3v2_check_C3_chk*_ep0_attempt001', 'c3v2_check_C4_chk*_ep0_attempt001')
            for d in sorted((BASE/'runs').glob(pattern)) if not only or d.name in only]
    rows, divergences, per_run = [], [], []
    started = time.monotonic()
    with wall.job(BASE, 'C3-v2 gap diagnosis: pipeline test and like-for-like'):
        for run in runs:
            per_run.append(score_run(run, models, rows, divergences))
            print(json.dumps(per_run[-1] | dict(wall_s=round(time.monotonic()-started))), flush=True)
            if divergences:
                break
    passed = not divergences and all(r['max_abs_xy_m'] <= TOLERANCE and r['max_abs_yaw_rad'] <= TOLERANCE for r in per_run)
    result = dict(schema='c3v2_gap_pipeline_and_like_for_like.v1', label='Diagnosis on check mazes; validation and sealed sets untouched',
                  tolerance=TOLERANCE, pipeline_test=dict(passed=passed, runs=per_run, first_divergence=divergences[0] if divergences else None,
                  max_abs_xy_m=max(r['max_abs_xy_m'] for r in per_run), max_abs_yaw_rad=max(r['max_abs_yaw_rad'] for r in per_run),
                  compared_values=sum(r['compared_values'] for r in per_run), decisions=sum(r['decisions'] for r in per_run)),
                  like_for_like=summarise(rows) if passed else 'not interpreted: pipeline test failed',
                  forward_executed_rows=rows, scorer_sha256=sha(__file__))
    owner.save(Path(out) if out else ROOT/'pipeline_and_like_for_like.json', result)
    print(json.dumps(dict(pipeline_test={k: v for k, v in result['pipeline_test'].items() if k != 'runs'},
                          like_for_like=result['like_for_like']), indent=1))


def merge(parts):
    """Combine subset results (disjoint missions, run in parallel) into the diagnosis result."""
    output.install(BASE)
    loaded = [json.loads(Path(part).read_text()) for part in parts]
    order = [d.name for pattern in ('c3v2_check_C3_chk*_ep0_attempt001', 'c3v2_check_C4_chk*_ep0_attempt001') for d in sorted((BASE/'runs').glob(pattern))]
    per_run = sorted((r for part in loaded for r in part['pipeline_test']['runs']), key=lambda r: order.index(r['run']))
    assert [r['run'] for r in per_run] == order, 'every fresh-check C3/C4 mission scored exactly once'
    divergences = sorted((part['pipeline_test']['first_divergence'] for part in loaded if part['pipeline_test']['first_divergence']),
                         key=lambda d: (order.index(d['run']), d['decision']))
    rows = [r for part in loaded for r in part['forward_executed_rows']]
    passed = all(part['pipeline_test']['passed'] for part in loaded)
    result = dict(schema='c3v2_gap_pipeline_and_like_for_like.v1', label='Diagnosis on check mazes; validation and sealed sets untouched',
                  tolerance=TOLERANCE, pipeline_test=dict(passed=passed, runs=per_run, first_divergence=divergences[0] if divergences else None,
                  max_abs_xy_m=max(r['max_abs_xy_m'] for r in per_run), max_abs_yaw_rad=max(r['max_abs_yaw_rad'] for r in per_run),
                  compared_values=sum(r['compared_values'] for r in per_run), decisions=sum(r['decisions'] for r in per_run)),
                  like_for_like=summarise(rows) if passed else 'not interpreted: pipeline test failed',
                  forward_executed_rows=rows, parts={str(p): sha(p) for p in parts}, scorer_sha256=sha(__file__))
    owner.save(ROOT/'pipeline_and_like_for_like.json', result)
    print(json.dumps(dict(pipeline_test={k: v for k, v in result['pipeline_test'].items() if k != 'runs'},
                          like_for_like=result['like_for_like']), indent=1))


if __name__ == '__main__':
    import argparse
    p = argparse.ArgumentParser()
    p.add_argument('--only', nargs='*')
    p.add_argument('--out', help='output path for a subset or smoke test (default: the diagnosis result)')
    p.add_argument('--merge', nargs='*', help='subset result files to combine')
    a = p.parse_args()
    merge(a.merge) if a.merge else main(a.only, a.out)
